const data = [
    {
        id: "1",
        name: "Brimstone",
        role:"Controller",
        abilities:"Incendiary | Sky Smoke | Stim Beacon | Orbital Strike",
        description: "Joining from the U.S.A., Brimstone's orbital arsenal ensures his squad always has the advantage. His ability to deliver utility precisely and safely make him the unmatched boots-on-the-ground commander.",
    },
    {
        id: "2",
        name: "Phoenix",
        role:"Duelist",
        abilities:"Curveball | Hot Hands | Blaze | Run It Back",
        description: "Hailing from the U.K., Phoenix's star power shines through in his fighting style, igniting the battlefield with flash and flare. Whether he's got backup or not, he'll rush into a fight on his own terms.",
    },
    {
        id: "3",
        name: "Sage",
        role:"Duelist",
        abilities:"Slow Orb | Healing Orb | Barrier Orb | Resurrection",
        description: "The stronghold of China, Sage creates safety for herself and her team wherever she goes. Able to revive fallen friends and stave off aggressive pushes, she provides a calm center to a hellish fight.",
    },
    {
        id: "4",
        name: "Sova",
        role:"Initiator",
        abilities:"Shock Bolt | Recon Bolt | Owl Drone | Hunter's Fury",
        description: "Born from the eternal winter of Russia's tundra, Sova tracks, finds, and eliminates enemies with ruthless efficiency and precision. His custom bow and incredible scouting abilities ensure that even if you run, you cannot hide.",
    },
    {
        id: "5",
        name: "Viper",
        role:"Controller",
        abilities:"Poison Cloud | Toxic Screen | Snake Bite | Viper's Pit",
        description: "The American Chemist, Viper deploys an array of poisonous chemical devices to control the battlefield and choke the enemy's vision. If the toxins don't kill her prey, her mindgames surely will.",
    },
    {
        id: "6",
        name: "Cypher",
        role:"Sentinel",
        abilities:"Cyber Cage | Spycam | Trapwire | Neural Theft",
        description: "The Moroccan information broker, Cypher is a one-man surveillance network who keeps tabs on the enemy's every move. No secret is safe. No maneuver goes unseen. Cypher is always watching.",
    },
    {
        id: "7",
        name: "Reyna",
        role:"Duelist",
        abilities:"Poison Cloud | Toxic Screen | Snake Bite | Viper's Pit",
        description: "Forged in the heart of Mexico, Reyna dominates single combat, popping off with each kill she scores. Her capability is only limited by her raw skill, making her highly dependent on performance.",
    },
    {
        id: "8",
        name: "Killjoy",
        role:"Sentinel",
        abilities:"Poison Cloud | Toxic Screen | Snake Bite | Viper's Pit",
        description: "The genius of Germany. Killjoy secures the battlefield with ease using her arsenal of inventions. If the damage from her gear doesn't stop her enemies, her robots' debuff will help make short work of them.",
    },
    {
        id: "9",
        name: "Breach",
        role:"Initiator",
        abilities:"Poison Cloud | Toxic Screen | Snake Bite | Viper's Pit",
        description: "Breach, the bionic Swede, fires powerful, targeted kinetic blasts to aggressively clear a path through enemy ground. The damage and disruption he inflicts ensures no fight is ever fair.",
    },
    {
        id: "10",
        name: "Omen",
        role:"Controller",
        abilities:"Poison Cloud | Toxic Screen | Snake Bite | Viper's Pit",
        description: "A phantom of a memory, Omen hunts in the shadows. He renders enemies blind, teleports across the field, then lets paranoia take hold as his foe scrambles to learn where he might strike next.",
    },
    {
        id: "11",
        name: "Jett",
        role:"Duelist",
        abilities:"Poison Cloud | Toxic Screen | Snake Bite | Viper's Pit",
        description: "Representing her home country of South Korea, Jett's agile and evasive fighting style lets her take risks no one else can. She runs circles around every skirmish, cutting enemies before they even know what hit them.",
    },
    {
        id: "12",
        name: "Raze",
        role:"Duelist",
        abilities:"Poison Cloud | Toxic Screen | Snake Bite | Viper's Pit",
        description: "Raze explodes out of Brazil with her big personality and big guns. With her blunt-force-trauma playstyle, she excels at flushing entrenched enemies and clearing tight spaces with a generous dose of 'boom.'",
    },
    {
        id: "13",
        name: "Skye",
        role:"Initiator",
        abilities:"Poison Cloud | Toxic Screen | Snake Bite | Viper's Pit",
        description: "Hailing from Australia, Skye and her band of beasts trail-blaze the way through hostile territory. With her creations hampering the enemy, and her power to heal others, the team is strongest and safest by Skye’s side.",
    },
    {
        id: "14",
        name: "Yoru",
        role:"Duelist",
        abilities:"Poison Cloud | Toxic Screen | Snake Bite | Viper's Pit",
        description: "Japanese native, Yoru, rips holes straight through reality to infiltrate enemy lines unseen. Using deception and aggression in equal measure, he gets the drop on each target before they know where to look.",
    },
    {
        id: "15",
        name: "Astra",
        role:"Controller",
        abilities:"Poison Cloud | Toxic Screen | Snake Bite | Viper's Pit",
        description: "Ghanaian Agent Astra harnesses the energies of the cosmos to reshape battlefields to her whim. With full command of her astral form and a talent for deep strategic foresight, she's always eons ahead of her enemy's next move.",
    },
    {
        id: "16",
        name: "Kay/o",
        role:"Initiator",
        abilities:"Poison Cloud | Toxic Screen | Snake Bite | Viper's Pit",
        description: "KAY/O is a machine of war built for a single purpose: neutralizing radiants. His power to Suppress enemy abilities dismantles his opponents' capacity to fight back, securing him and his allies the ultimate edge.",
    },
    {
        id: "17",
        name: "Chamber",
        role:"Sentinel",
        abilities:"Poison Cloud | Toxic Screen | Snake Bite | Viper's Pit",
        description: "Well-dressed and well-armed, French weapons designer Chamber expels aggressors with deadly precision. He leverages his custom arsenal to hold the line and pick off enemies from afar, with a contingency built for every plan.",
    },
    {
        id: "18",
        name: "Neon",
        role:"Duelist",
        abilities:"Poison Cloud | Toxic Screen | Snake Bite | Viper's Pit",
        description: "Filipino Agent Neon surges forward at shocking speeds, discharging bursts of bioelectric radiance as fast as her body generates it. She races ahead to catch enemies off guard, then strikes them down quicker than lightning.",
    },
    {
        id: "19",
        name: "Fade",
        role:"Initiator",
        abilities:"Poison Cloud | Toxic Screen | Snake Bite | Viper's Pit",
        description: "Turkish bounty hunter, Fade, unleashes the power of raw nightmares to seize enemy secrets. Attuned with terror itself, she hunts targets and reveals their deepest fears—before crushing them in the dark.",
    },
    {
        id: "20",
        name: "Harbor",
        role:"Controller",
        abilities:"Poison Cloud | Toxic Screen | Snake Bite | Viper's Pit",
        description: "Hailing from India’s coast, Harbor storms the field wielding ancient technology with dominion over water. He unleashes frothing rapids and crushing waves to shield his allies, or pummel those that oppose him.",
    },
    {
        id: "21",
        name: "Gekko",
        role:"Initiator",
        abilities:"Poison Cloud | Toxic Screen | Snake Bite | Viper's Pit",
        description: "Gekko the Angeleno leads a tight-knit crew of calamitous creatures. His buddies bound forward, scattering enemies out of the way, with Gekko chasing them down to regroup and go again.",
    },
    {
        id: "22",
        name: "Deadlock",
        role:"Sentinel",
        abilities:"Poison Cloud | Toxic Screen | Snake Bite | Viper's Pit",
        description: "Norwegian operative Deadlock deploys an array of cutting-edge nanowire to secure the battlefield from even the most lethal assault. No one escapes her vigilant watch, nor survives her unyielding ferocity.",
    },
    {
        id: "23",
        name: "Iso",
        role:"Duelist",
        abilities:"Poison Cloud | Toxic Screen | Snake Bite | Viper's Pit",
        description: "Chinese fixer for hire, Iso falls into a flow state to dismantle the opposition. Reconfiguring ambient energy into bulletproof protection, he advances with focus towards his next duel to the death.",
    },
    {
        id: "24",
        name: "Clove",
        role:"Controller",
        abilities:"Poison Cloud | Toxic Screen | Snake Bite | Viper's Pit",
        description: "Scottish troublemaker Clove makes mischief for enemies in both the heat of combat and the cold of death. The young immortal keeps foes guessing, even from beyond the grave, their return to the living only ever a moment away.",
    },
    {
        id: "25",
        name: "vyse",
        role:"Sentinel",
        abilities:"Poison Cloud | Toxic Screen | Snake Bite | Viper's Pit",
        description: "Metallic mastermind Vyse unleashes liquid metal to isolate, trap, and disarm her enemies. Through cunning and manipulation, she forces all who oppose her to fear the battlefield itself.",
    },
    {
        id: "26",
        name: "Tejo",
        role:"Initiator",
        abilities:"Poison Cloud | Toxic Screen | Snake Bite | Viper's Pit",
        description: "A veteran intelligence consultant from Colombia, Tejo's ballistic guidance system pressures the enemy to relinquish their ground - or their lives. His targeted strikes keep opponents off balance and under his heel.",
    },
    {
        id: "27",
        name: "Waylay",
        role:"Duelist",
        abilities:"Poison Cloud | Toxic Screen | Snake Bite | Viper's Pit",
        description: "Thailand's prismatic radiant Waylay transforms into light itself as she darts across the battlefield, striking down her targets through shards of light before flitting back to safety, all in the blink of an eye.",
    },
    
]

export default data;